### ISSUE TITLE
菜单绑定的物品必须右键方块打开，右键空气无效果

### ISSUE THREAD

**Issue by postyizhan** [Arasple/Invero#20]
我配置了打开菜单的物品，我必须手持这个物品右键方块才可以打开菜单，不能右键空气打开
QQ：185839426
核心：https://github.com/LeavesMC/Leaves
版本：1.19.4
插件：Invero-1.0.8-pre-3
日志：无报错
复现步骤：
> menu:
  title: '&7| &a主菜单'
bindings:
  chat: '/menu'
  item: 'clock'

**Comment by Arasple** [comment]
fixed in pre4
