### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Zarkness** [Arasple/Invero#3]
I was looking at the plugin documentation and I saw that it says that the payment system is "pay what you want" and then has paid services where it already has a defined price and I was wondering.

If I for example donated 10 dollars I would have the premium service/plan or which one would I have? 

Would there be a way to pay only once and not have to pay annually? I would like to get the permanent premium plan but I think that the current price is too expensive for what it offers.

The support group you mention where would it be done?

and another thing as I do to compile the plugin as plugin because it is the first time I see the system that if called from the plugin folder to compile the plugin but if called from the framework folder is compiled as framework and if I want to compile for both at once how do I do?

**Comment by Arasple** [comment]
HelloThe reference provided in this document is not final pricingAnd the services I plan to provide may differ between my country and abroadFor non-Chinese paid communities, it will be available on the Discord server. Pricing is estimated to be around $20 (permanent)Please wait for the official release of the English version (expected in summer)On Feb 19, 2023, at 05:25, Zarkness ***@***.***> wrote:﻿
I was looking at the plugin documentation and I saw that it says that the payment system is "pay what you want" and then has paid services where it already has a defined price and I was wondering.
If I for example donated 10 dollars I would have the premium service/plan or which one would I have?
Would there be a way to pay only once and not have to pay annually? I would like to get the permanent premium plan but I think that the current price is too expensive for what it offers.
The support group you mention where would it be done?

**Comment by Arasple** [comment]
Hello

The reference provided in this document is not final pricing
And the services I plan to provide may differ between my country and abroad

For non-Chinese paid communities, it will be available on the Discord server. Pricing is estimated to be around $20 (permanent)

Please wait for the official release of the English version (expected in summer)

**Comment by Arasple** [comment]
You have to compile the entire project and get the plug-in jar under module ”plugin:platform-bukkit”

**Comment by Zarkness** [comment]
Hi, @Arasple I was trying to compile the latest version of the plugin and I couldn't compile it, could you help me?
